Student.create(first_name: "Angelyse", last_name: "Rosado", grade: 6, klass: 602)
Student.create(first_name: "Helen", last_name: "Cordero", grade: 6, klass: 602)
Student.create(first_name: "Shaniya", last_name: "Percell", grade: 6, klass: 602)
Student.create(first_name: "David", last_name: "Dalum", grade: 6, klass: 602)
Student.create(first_name: "Melvyn", last_name: "Parra", grade: 6, klass: 602)
Student.create(first_name: "Jeymi", last_name: "Estevez", grade: 6, klass: 602)
Student.create(first_name: "David", last_name: "Reyes", grade: 6, klass: 602)
Student.create(first_name: "Ezequiel", last_name: "Pujols", grade: 6, klass: 602)
Student.create(first_name: "Chairys", last_name: "Martinez", grade: 6, klass: 602)
Student.create(first_name: "Lamani", last_name: "Junious", grade: 6, klass: 602)
Student.create(first_name: "Amara", last_name: "Tourey", grade: 6, klass: 602)
Student.create(first_name: "John", last_name: "Jones", grade: 6, klass: 602)

mrsarli = Teacher.create(name: "Mr. Sarli", email: "adam@gmail.com")
mrsarli.klasses.create(name: "602", subject: "math", grade: "6th", period: 3)

Student.create(first_name: "Elizabeth", last_name: "Mata", grade: 7, klass: 703)
Student.create(first_name: "Angie", last_name: "Pena", grade: 7, klass: 703)
Student.create(first_name: "Richard", last_name: "Fernandez", grade: 7, klass: 703)
Student.create(first_name: "Jeffrey", last_name: "Gutierrez", grade: 7, klass: 703)
Student.create(first_name: "Shaneal", last_name: "Dacres", grade: 7, klass: 703)
Student.create(first_name: "Erica", last_name: "Surita", grade: 7, klass: 703)
Student.create(first_name: "Yarieliz", last_name: "Rivera", grade: 7, klass: 703)
Student.create(first_name: "Jaycob", last_name: "Cutler", grade: 7, klass: 703)
Student.create(first_name: "Johanni", last_name: "Garcia-Santana", grade: 7, klass: 703)
Student.create(first_name: "Richie", last_name: "Rodriguez", grade: 7, klass: 703)
